[workspace]
authors = ["pathak-aman <amanpathak2909@gmail.com>"]
channels = ["conda-forge"]
name = "learning_langgraph"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
langgraph = ">=0.6.9,<0.7"
langchain-core = ">=0.3.78,<0.4"
langchain-openai = ">=0.3.35,<0.4"
python-dotenv = ">=1.1.1,<2"
ipykernel = ">=6.30.1,<7"
